### ISSUE TITLE
Fixing external links

### ISSUE THREAD

**Issue by vincentdavis** [biopython/biopython.github.io#32] opened 2016-04-20 01:46 UTC
Below attatched file is a list.
see also issue #19

[Bad external links April 19 2016.xlsx](https://github.com/biopython/biopython.github.io/files/227111/Bad.external.links.April.19.2016.xlsx)

**Comment by peterjc** [comment] 2016-04-29 16:12
I've going to close this as a duplicate of #19.

**Closed** 2016-04-29 16:13 UTC
