### ISSUE TITLE
Download links not working for Mac OSx?

### ISSUE THREAD

**Issue by maryame** [biopython/biopython.github.io#55] opened 2016-04-25 16:11 UTC
When I click either the tar.gz or the zip file I get a 404 error
The windows links work just fine
Anybody else?

http://biopython.org/DIST/biopython-1.66.tar.gz

**Comment by MarkusPiotrowski** [comment] 2016-04-25 19:44
These two (and others) have not been uploaded yet. If you want to install Biopython see the "Installation Instructions" further down on the Download page. You can also download the source from 
https://pypi.python.org/pypi/biopython/1.66

**Comment by peterjc** [comment] 2016-04-25 21:19
Sadly yes, but as Markus notes you can download the recent tar-balls from PyPI.

Closing as a duplicate of #7

**Closed by peterjc** 2016-04-25 21:19 UTC

**Comment by peterjc** [comment] 2016-04-26 12:51
This particular file was uploaded this morning via https://github.com/biopython/DIST/commit/cfa36fc1a11c9b976f45d4f9d0524cb891895052
